In [80]:
import pandas as pd 
#import pandas_alive
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np 
from summarytools import dfSummary

ETL Extracción, transformación y carga de los datos.

lectura de los datasets.

In [52]:
homicidios_hecho = pd.read_excel("Datasets/homicidios.xlsx", sheet_name="HECHOS")
homicidios_victima = pd.read_excel("Datasets/homicidios.xlsx", sheet_name="VICTIMAS")
comuna = pd.read_excel("Datasets/comunas.xlsx")


Vamos a trabajar con lo datos de homicidios, especificamente  en la tabla de hechos.

In [20]:
print(homicidios_hecho.info())
homicidios_hecho.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   ID                     696 non-null    object        
 1   N_VICTIMAS             696 non-null    int64         
 2   FECHA                  696 non-null    datetime64[ns]
 3   AAAA                   696 non-null    int64         
 4   MM                     696 non-null    int64         
 5   DD                     696 non-null    int64         
 6   HORA                   696 non-null    object        
 7   HH                     696 non-null    object        
 8   LUGAR_DEL_HECHO        696 non-null    object        
 9   TIPO_DE_CALLE          696 non-null    object        
 10  Calle                  695 non-null    object        
 11  Altura                 129 non-null    float64       
 12  Cruce                  525 non-null    object        
 13  Direc

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA HH  \
0  2016-0001           1 2016-01-01  2016   1   1  04:00:00  4   
1  2016-0002           1 2016-01-02  2016   1   2  01:15:00  1   
2  2016-0003           1 2016-01-03  2016   1   3  07:00:00  7   
3  2016-0004           1 2016-01-10  2016   1  10  00:00:00  0   
4  2016-0005           1 2016-01-21  2016   1  21  05:20:00  5   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE  ...  Altura  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...     NaN   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...     NaN   
2                         AV ENTRE RIOS 2034       AVENIDA  ...  2034.0   
3      AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...     NaN   
4  AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...     NaN   

                                 Cruce  \
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                  DE LOS CORRALES AV.   
2                                  NaN   
3             VILLEGAS, CONRADO, GRAL.   
4              SAENZ PE?A, LUIS, PRES.   

                               Dirección Normalizada COMUNA  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...      8   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.      9   
2                                ENTRE RIOS AV. 2034      1   
3          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.      8   
4            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.      1   

                                 XY (CABA)         pos x         pos y  \
0    Point (98896.78238426 93532.43437792)  -58.47533969  -34.68757022   
1    Point (95832.05571093 95505.41641999)  -58.50877521  -34.66977709   
2   Point (106684.29090040 99706.57687843)  -58.39040293  -34.63189362   
3    Point (99840.65224780 94269.16534422)  -58.46503904  -34.68092974   
4  Point (106980.32827929 100752.16915795)  -58.38718297  -34.62246630   

    PARTICIPANTES VICTIMA    ACUSADO  
0       MOTO-AUTO    MOTO       AUTO  
1  AUTO-PASAJEROS    AUTO  PASAJEROS  
2       MOTO-AUTO    MOTO       AUTO  
3         MOTO-SD    MOTO         SD  
4  MOTO-PASAJEROS    MOTO  PASAJEROS  

[5 rows x 21 columns]

Vamos a proceder a estudiar  lo valores nulos  de este dataset.


In [21]:
valores =homicidios_hecho.isnull().sum()
print(valores)

ID                         0
N_VICTIMAS                 0
FECHA                      0
AAAA                       0
MM                         0
DD                         0
HORA                       0
HH                         0
LUGAR_DEL_HECHO            0
TIPO_DE_CALLE              0
Calle                      1
Altura                   567
Cruce                    171
Dirección Normalizada      8
COMUNA                     0
XY (CABA)                  0
pos x                      0
pos y                      0
PARTICIPANTES              0
VICTIMA                    0
ACUSADO                    0
dtype: int64


Podemos observar  que lo valores nulos están concentrados en las columnas  calle, Altura y Cruce. Vamos a proceder hacer un estudio de manera detallada.

In [22]:
selected_Estudio = homicidios_hecho[['Altura', 'Calle', 'Dirección Normalizada', 'Cruce']]

In [10]:
selected_Estudio.head()

Altura             Calle  \
0     NaN  PIEDRA BUENA AV.   
1     NaN    PAZ, GRAL. AV.   
2  2034.0    ENTRE RIOS AV.   
3     NaN    LARRAZABAL AV.   
4     NaN      SAN JUAN AV.   

                               Dirección Normalizada  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.   
2                                ENTRE RIOS AV. 2034   
3          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.   
4            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.   

                                 Cruce  
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.  
1                  DE LOS CORRALES AV.  
2                                  NaN  
3             VILLEGAS, CONRADO, GRAL.  
4              SAENZ PE?A, LUIS, PRES.

In [23]:
selected_Estudio.isnull()

Altura  Calle  Dirección Normalizada  Cruce
0      True  False                  False  False
1      True  False                  False  False
2     False  False                  False   True
3      True  False                  False  False
4      True  False                  False  False
..      ...    ...                    ...    ...
691    True  False                  False  False
692    True  False                  False  False
693    True  False                  False  False
694   False  False                  False   True
695   False  False                  False   True

[696 rows x 4 columns]

Al estudiar el  dataset, podemos tomar las siguientes desiciones en cuanto a los valores nulos:
- Para el caso de la columna **calle** tenemos un solo dato nulo.
- La columna **dirección Normalizada** contiene 8 nulos.
- La columna **Cruce** no enontramos con 171 valores nulos, esto equivale a 24.56% de los datos de la columna.
- Para la columna altura tiene un total de 567 nulos, esto representa el 81,5% de datos de la columna.

Con respecto a la culumna **Calle**  , la dejaremos sin nungun tipo de modificación, la columna **dirección normalizada** no tiene alternativa de poder completarse con las columnas del dataset, solo contiene el 1.1% de nulos por lo que la conservaremos. 
La columna **cruce** solo va ha  tener datos cuando el hecho se produce en un cruce de calles, por tal motivo la  vamos  a conservar.

Al observar  la columna altura prodedemos a eliminarla, debido a la gran cantidad de valores faltantes, en este sentido no hay posibilidad de rellenar columna.


In [24]:
homicidios_hecho= homicidios_hecho.drop("Altura", axis=1)
homicidios_hecho.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   ID                     696 non-null    object        
 1   N_VICTIMAS             696 non-null    int64         
 2   FECHA                  696 non-null    datetime64[ns]
 3   AAAA                   696 non-null    int64         
 4   MM                     696 non-null    int64         
 5   DD                     696 non-null    int64         
 6   HORA                   696 non-null    object        
 7   HH                     696 non-null    object        
 8   LUGAR_DEL_HECHO        696 non-null    object        
 9   TIPO_DE_CALLE          696 non-null    object        
 10  Calle                  695 non-null    object        
 11  Cruce                  525 non-null    object        
 12  Dirección Normalizada  688 non-null    object        
 13  COMUN

Vamos a estudiar los valores duplicados.

In [27]:
duplicados= homicidios_hecho.duplicated().sum()
print(duplicados)

0


Observamos que no tenemos duplicados.

vamos a transformar los valores de la columna HH a tipo numérico, ya que estan tipo object.

In [28]:
# Cambio el dato horas  a tipo de dato numerico y luego a entero 
homicidios_hecho["HH"] = pd.to_numeric(homicidios_hecho ["HH"], errors="coerce")
homicidios_hecho["HH"] = homicidios_hecho["HH"].astype("Int64")

Las coordenadas X y Y debemos  transformar el tipo de dato ya que  estan en tipo Objeto.  estan deben para a tipo float(), tambien debemos revisar que  posicionen no son válidas.

In [41]:
# Filtrar filas con posiciones no válidas
valid_positions = ~(homicidios_hecho['pos x'].str.contains('[^0-9.,-]') | homicidios_hecho['pos y'].str.contains('[^0-9.,-]') )



In [42]:
# Establecer posiciones no válidas en NaN
homicidios_hecho.loc[~valid_positions, ['pos x', 'pos y']] = np.nan


In [45]:
homicidios_hecho['pos y'] = pd.to_numeric(homicidios_hecho['pos y'].str.replace(',', '.'), errors='coerce')

Aca transformamos los valores de latitud y  longitud a tipo float.

In [50]:
homicidios_hecho['pos x'] = pd.to_numeric(homicidios_hecho['pos x'].astype(str).str.replace(',', '.'), errors='coerce').astype(float)
homicidios_hecho['pos y'] = pd.to_numeric(homicidios_hecho['pos y'].astype(str).str.replace(',', '.'), errors='coerce').astype(float)

In [51]:
homicidios_hecho.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   ID                     696 non-null    object        
 1   N_VICTIMAS             696 non-null    int64         
 2   FECHA                  696 non-null    datetime64[ns]
 3   AAAA                   696 non-null    int64         
 4   MM                     696 non-null    int64         
 5   DD                     696 non-null    int64         
 6   HORA                   696 non-null    object        
 7   HH                     695 non-null    Int64         
 8   LUGAR_DEL_HECHO        696 non-null    object        
 9   TIPO_DE_CALLE          696 non-null    object        
 10  Calle                  695 non-null    object        
 11  Cruce                  525 non-null    object        
 12  Dirección Normalizada  688 non-null    object        
 13  COMUN

Vamos ha revisar el dataset que hemos traido de la pagina https://data.buenosaires.gob.ar/dataset/comunas donde se especifica el nombre de cada una de las comunas. esto con la finalidad de darle valor agregado al dataset, con esta información el dataset tendra información  de la descripción de cada una de las comunas con los barrios que la conforman.

In [53]:
comuna.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   ID         15 non-null     int64  
 1   OBJETO     15 non-null     object 
 2   COMUNAS    15 non-null     int64  
 3   BARRIOS    15 non-null     object 
 4   PERIMETRO  15 non-null     float64
 5   AREA       15 non-null     float64
dtypes: float64(2), int64(2), object(2)
memory usage: 852.0+ bytes


In [54]:
comuna.head()

ID          OBJETO  COMUNAS                                  BARRIOS  \
0   1  LIMITE COMUNAL        2                                 RECOLETA   
1   2  LIMITE COMUNAL        5                          ALMAGRO - BOEDO   
2   3  LIMITE COMUNAL        6                                CABALLITO   
3   4  LIMITE COMUNAL        7                FLORES - PARQUE CHACABUCO   
4   5  LIMITE COMUNAL        9  LINIERS - MATADEROS - PARQUE AVELLANEDA   

      PERIMETRO          AREA  
0  21452.838648  6.317265e+06  
1  12323.432479  6.660603e+06  
2  10990.964471  6.851029e+06  
3  17972.257870  1.242290e+07  
4  21411.738344  1.650531e+07

In [69]:
print(homicidios_hecho.columns)

Index(['ID', 'N_VICTIMAS', 'FECHA', 'AAAA', 'MM', 'DD', 'HORA', 'HH',
       'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'Calle', 'Altura', 'Cruce',
       'Dirección Normalizada', 'COMUNA', 'XY (CABA)', 'pos x', 'pos y',
       'PARTICIPANTES', 'VICTIMA', 'ACUSADO'],
      dtype='object')


Debemos renombrar el nombre de la columna COMUNA a COMUNAS  para poder realizar el merge.

In [71]:
homicidios_hecho=homicidios_hecho.rename(columns={
    "COMUNA": "COMUNAS"
})

In [72]:
print(homicidios_hecho.columns)

Index(['ID', 'N_VICTIMAS', 'FECHA', 'AAAA', 'MM', 'DD', 'HORA', 'HH',
       'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'Calle', 'Altura', 'Cruce',
       'Dirección Normalizada', 'COMUNAS', 'XY (CABA)', 'pos x', 'pos y',
       'PARTICIPANTES', 'VICTIMA', 'ACUSADO'],
      dtype='object')


In [74]:

homicidios_hecho = homicidios_hecho.merge(comuna, on="COMUNAS", how="left")


Vamos a crear una nueva columna con el nombre del  dia de la semana que corresponde el siniestro, con esto podremos  ver como  es el comportamiento de  los siniestros por cada dia, podriamos estudiar los fines de semana en conjunto tambien y comparar con los dias de semana. 

In [77]:
#Creo una columna nueva `Día semana` que contenga el nombre del día de la semana
homicidios_hecho['DIA SEMANA'] = homicidios_hecho['FECHA'].dt.strftime('%A')

#Creo un diccionario para modificar a español los nombres de los dás de la semana y lo aplico a la columna nueva
dic={  'Friday':'Viernes',
       'Saturday': 'Sabado',
       'Sunday': 'Domingo',  
       'Thursday': 'Jueves',
        'Monday': 'Lunes',
        'Wednesday': 'Miercoles',
       'Tuesday': 'Martes'}
homicidios_hecho['DIA SEMANA'] =homicidios_hecho['DIA SEMANA'].replace(dic)

In [78]:
homicidios_hecho.head()

ID_x  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA HH  \
0  2016-0001           1 2016-01-01  2016   1   1  04:00:00  4   
1  2016-0002           1 2016-01-02  2016   1   2  01:15:00  1   
2  2016-0003           1 2016-01-03  2016   1   3  07:00:00  7   
3  2016-0004           1 2016-01-10  2016   1  10  00:00:00  0   
4  2016-0005           1 2016-01-21  2016   1  21  05:20:00  5   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE  ...         pos y  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...  -34.68757022   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...  -34.66977709   
2                         AV ENTRE RIOS 2034       AVENIDA  ...  -34.63189362   
3      AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...  -34.68092974   
4  AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...  -34.62246630   

    PARTICIPANTES VICTIMA    ACUSADO  ID_y          OBJETO  \
0       MOTO-AUTO    MOTO       AUTO  12.0  LIMITE COMUNAL   
1  AUTO-PASAJEROS    AUTO  PASAJEROS   5.0  LIMITE COMUNAL   
2       MOTO-AUTO    MOTO       AUTO  14.0  LIMITE COMUNAL   
3         MOTO-SD    MOTO         SD  12.0  LIMITE COMUNAL   
4  MOTO-PASAJEROS    MOTO  PASAJEROS  14.0  LIMITE COMUNAL   

                                             BARRIOS     PERIMETRO  \
0     VILLA LUGANO - VILLA RIACHUELO - VILLA SOLDATI  20935.012513   
1            LINIERS - MATADEROS - PARQUE AVELLANEDA  21411.738344   
2  CONSTITUCION - MONTSERRAT - PUERTO MADERO - RE...  36102.201573   
3     VILLA LUGANO - VILLA RIACHUELO - VILLA SOLDATI  20935.012513   
4  CONSTITUCION - MONTSERRAT - PUERTO MADERO - RE...  36102.201573   

           AREA DIA SEMANA  
0  2.221690e+07    Viernes  
1  1.650531e+07     Sabado  
2  1.779457e+07    Domingo  
3  2.221690e+07    Domingo  
4  1.779457e+07     Jueves  

[5 rows x 27 columns]

In [81]:
dfSummary(homicidios_hecho)